%YAML:1.0
# 使用冒号:代表，格式为key: value。冒号后面要加一个空格：
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/riki/Desktop/rgbd_dataset_freiburg1_xyz

# camera intrinsics相机内参
# fx,fy分别是相机x,y方向的焦距, cx,cy分别是相机的光心
# fr1
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 318.6
camera.cy: 255.3

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

# 相机的深度尺度
camera.depth_scale: 5000

# VO Parameters
# ORB特征提取, 关键点的检测和描述子的计算
number_of_features: 500 # 最多提取的特征点数量
scale_factor: 1.2  # 金字塔图像的尺度参数
level_pyramid: 4   # 高斯金字塔的层数
match_ratio: 2.0   #  好的匹配点的筛选系数
max_num_lost: 10   # 连续跟踪丢失的次数
min_inliers: 30    # 最少的内点的数量
# 关键帧标准，最小旋转和平移
keyframe_rotation: 0.1       # 两个关键帧之间最小的旋转大小
keyframe_translation: 0.1    # 两个关键帧之间最小的平移大小
# 匹配率=匹配次数/可见次数, 最低匹配次数
map_point_erase_ratio: 0.1   # 删除路标点的系数
